---
# the host in which the playbook wiil be run
- hosts: localhost
  # in this example, we use the localhost, so this is needed
  connection: localhost

  # the target user Ansible will impersonate when provisioning
  user: archie

  # this prevents all tasks to run with sudo by default
  sudo: false

  # additional variables
  vars:
    users: johndoe

  # roles are a way to group tasks; they will run in the sequence determined
  # here
  roles:
    #- system
    #- archlinux
    - docker

# the host in which the playbook will be run
- hosts: aws_host
  # in this example, we use the localhost, so this is needed
  connection: smart

  # the target user Ansible will impersonate when provisioning
  user: ec2-user

  # this prevents all tasks to run with sudo by default
  sudo: false

  # additional variables
  vars:
    users: johndoe

  # roles are a way to group tasts; they will run in the sequence determined
  # here
  roles:
    # - system
    # - amazonlinux
    - docker
